# Site settings
title: The Quantum Tunnel
name: Meet Udeshi
email: mudeshi1209@gmail.com
phone: +91-9619221240
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://udiboy1209.github.io" # the base hostname & protocol for your site
github_username: udiboy1209
fb_id: 1611542573

# Build settings
markdown: kramdown
highlighter: rouge

jquery: 2.1.4
